# Generated by Django 3.0.5 on 2020-05-01 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservices',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subservices',
            name='basic_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Services', verbose_name='Главная услуга'),
        ),
        migrations.AlterField(
            model_name='subservices',
            name='image',
            field=models.ImageField(upload_to='services_image', verbose_name='Картинка'),
        ),
    ]
