# Generated by Django 3.0.5 on 2020-05-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20200502_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservices',
            name='image',
            field=models.ImageField(upload_to='media/services_image', verbose_name='Картинка'),
        ),
    ]
