# Generated by Django 3.0.5 on 2020-05-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20200502_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservices',
            name='image',
            field=models.ImageField(upload_to='services_image', verbose_name='Картинка'),
        ),
    ]
