# Generated by Django 3.0.5 on 2020-05-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20200502_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservices',
            name='description',
            field=models.TextField(max_length=700, verbose_name='Описание'),
        ),
    ]
