# Generated by Django 3.0.5 on 2020-05-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20200502_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example_photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='example_image', verbose_name='Картинка')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('basic_subservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Subservices', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Пример',
                'verbose_name_plural': 'Примеры',
            },
        ),
    ]
