# Generated by Django 3.0.5 on 2020-05-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_example_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example_photos',
            name='image',
            field=models.FileField(upload_to='example_image', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='subservices',
            name='image',
            field=models.FileField(upload_to='services_image', verbose_name='Картинка'),
        ),
    ]
